### ISSUE TITLE
XML-Toolkit: SAM Template Area, Volume 

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#103]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by MajaLindroth** [comment]
This issue seems to have been fixed by the changes to the Environment_Engine earlier this year. Does not seem to be a problem anymore. I'm closing this issue.
