### ISSUE TITLE
XML-Toolkit: SAM Template Performance

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#104]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by FraserGreenroyd** [comment]
No longer required as not using the methods mentioned in the original issue comment.
