### ISSUE TITLE
XML_Toolkit: Correct Type recognition

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#142]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by FraserGreenroyd** [comment]
I think this comes down to the related BHoM issue (https://github.com/BHoM/BHoM/issues/338)

We need to go through our Environmental Types and realign to a generic approach that can be converted from Revit to generic and generic back to Revit, gbXML, TAS, etc.

**Comment by michaldengusiak** [comment]
ok with new approach this is now implemented...

and we have now windows recognized... further test to be done...initial solution
[Pull Revit - Push gbXML_02.zip](https://github.com/BHoM/XML_Toolkit/files/2750485/Pull.Revit.-.Push.gbXML_02.zip)
