### ISSUE TITLE
XML_Toolkit: Rename and merge with JSON_Toolkit

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/XML_Toolkit#152]
The Environmental JSON_Toolkit and XML_Toolkit are both built for the Green Building schema of their respective file types. This results in a lot of duplicated code across both projects.

Rename the XML_Toolkit to be the EnvironmentSerialisation_Toolkit (name up for debate - this is just a starter for ten) and consolidate the disparate code bases into a single maintainable solution. The JSON_Toolkit code does not contain anything which could not be included for Open Source so should suffer no ill side affects from that.

**Comment by rwemay** [comment]
I thought the XML_Toolkit was initially intended to be just that - a discipline/software agnostic repo of XML conversions, with discipline/software/schema specific projects. Looking at it now, it does look like it's a BEnv specific repo. Does having a single XML_Toolkit repo that deals with XML formatting/CRUD, then schema-specific projects inside it still make sense? 

I know there are at least a couple of other XML schema's to support for interop - Tekla/structures for example.

**Comment by rwemay** [comment]
Maybe worth a short wider discussion on strategy before any major refactoring? To make sure schema support/serialisation are aligned in general to minimise duplication, including between engine/other disciplines. @adecler , @al-fisher thoughts?

**Comment by al-fisher** [comment]
Hey @rwemay @FraserGreenroyd - agreed - be good to revisit the high level strategy and code architecture for these different flavours of serialisation to ensure easily expandable going forward.

First point - think it will be helpful to separate out more clearly the Adapter and CRUD aspects of the format/Toolkit - from the actual Conversion methods occurring in the Engine methods.   

The original intent was to have our generic `File_Adapter` handling much of the boilerplate CRUD.
With then a XML implemetation of it to make concrete. This may be unnecessary overhead so in this case you might be wise to stick with your `XML_Adapter` handing the file reading and writing directly- but worth considering.   

But then what I would look at doing is perhaps reorganising your Engine Projects more closely around the schemas and specific converts required.
Say a `GBXML_Engine`, `AnotherXML_Engine` ...

This should make managing and expanding the different variations easier - more scalable?
Up for a chat if useful?

**Comment by FraserGreenroyd** [comment]
Hi @al-fisher that's pretty much what I want to move towards to. The `XML_Toolkit` in its current state is solely Green Building Schema orientated - I want to move away from that so that we can achieve additional schemas (we have some lined up for SAP, there's the ones @rwemay mentioned for structures, etc.).

However, the big question here is regarding the serialisation of two different serialised types - `XML` and `JSON`. The Green Building JSON schema is, in terms of its required C# objects and conversions in and out of BHoM, identical to the Green Building XML schema. But to include JSON serialisation within this toolkit would make the naming a bit redundant (whoever heard of an XML toolkit producing a JSON file?) which is the big bit I'd like to resolve - whether we can:

1) Move away from XML into a more generic Serialisation Toolkit, capable of handling XML, JSON, and other serialised file types as we see fit later
2) Move away from solely gbXML schema as a knock on result.

2 can (and ultimately will) happen regardless because even if this remains XML specific it needs to generalise away from gbXML at its core, but question 1 there is the big one here, whether I can save myself having to maintain two toolkits of near identical code :smile:

**Comment by FraserGreenroyd** [comment]
Closing as the JSON prototype did not fulfil requirements nor provide any additional outcomes that were beneficial.
