### ISSUE TITLE
XML_Toolkit: IndividualSpaces order

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#159]
IndividualSpaces for TAS works but we seems to have wrong spaces

![image](https://user-images.githubusercontent.com/26113670/50981726-83104200-14f3-11e9-965c-20268c04a1a5.png)

![image](https://user-images.githubusercontent.com/26113670/50981822-bb178500-14f3-11e9-9eef-c83015a0e432.png)

but we have 
![image](https://user-images.githubusercontent.com/26113670/50981855-cbc7fb00-14f3-11e9-9ebb-37083d7e7327.png)
I think it takes geometry from B1_001 Car_Park to be determined

also wrong properties are used for construction we need to review and check this is internal floor so should be adiabatic in case for individual gbXML files
![image](https://user-images.githubusercontent.com/26113670/50982199-7fc98600-14f4-11e9-921d-fd18f5e45df0.png)

we should have door here `Doors_ver01: SIM_EXT_SLD_Vehicle `
![image](https://user-images.githubusercontent.com/26113670/50983947-88bc5680-14f8-11e9-9da3-1b88e85f267f.png)

**Comment by FraserGreenroyd** [comment]
@michaldengusiak can you confirm if this is still an issue? I'm wondering whether the fix for #160 may have also fixed this?

**Comment by michaldengusiak** [comment]
ok will test now... with current PR

**Comment by michaldengusiak** [comment]
still the same issue...
We need to fix `space names` and `order ` in XML it should match top image in this Issue 001, 002 etc...
![image](https://user-images.githubusercontent.com/26113670/51472939-df385900-1d72-11e9-8f03-58d9dab15469.png)

![image](https://user-images.githubusercontent.com/26113670/51473007-0d1d9d80-1d73-11e9-9ed4-d169e882525d.png)

**Comment by FraserGreenroyd** [comment]
Ok thanks will investigate then - just didn't want to spend time on it if it was fixed but will take a look :smile:

**Comment by michaldengusiak** [comment]
@FraserGreenroyd 
ok this is now better, we have now all spaces and correct references .
We need to fix:
1. Space Names
2. Space order
3.  Openings names 

![image](https://user-images.githubusercontent.com/26113670/51564403-1dbf3800-1e87-11e9-9c21-4b04cc5b1eff.png)

![image](https://user-images.githubusercontent.com/26113670/51564314-d20c8e80-1e86-11e9-9d5a-b7620e2b2420.png)

**Comment by FraserGreenroyd** [comment]
@michaldengusiak Sorry not sure I actually fully understand the bit about space order? Could you explain further? I will take a look at space naming and opening naming now.

**Comment by michaldengusiak** [comment]
@FraserGreenroyd for easier debugging and consistency between different softwares we need to have same space order as i source. So if we pull from Revit we need to keep Revit space order. It is default when we export gbXML using Revit and we need to replicate this process. So when we pull spaces we should use this as space order in gbXML
so for our standard template file we should have this
![image](https://user-images.githubusercontent.com/26113670/51624718-59afd700-1f33-11e9-80b0-fcc1859dcf1b.png)

and this is order from Revit native gbXML export
<img src="https://user-images.githubusercontent.com/26113670/51624858-a98e9e00-1f33-11e9-9567-531b201470a1.png" height=360>

**Comment by michaldengusiak** [comment]
@FraserGreenroyd 
ok we can now return to this issue... please use same test example from #209 
We are pulling right data form Revit and must have same naming and order in gmXML
![image](https://user-images.githubusercontent.com/26113670/52857984-ca0bdb80-3120-11e9-93ac-56c2d7884673.png)

currently when I look in gbXML we have
:
![image](https://user-images.githubusercontent.com/26113670/52858030-e9a30400-3120-11e9-8aea-c995773cdaef.png)

this is XML issue and if need we need to revise whole structure to get this under control

**Comment by FraserGreenroyd** [comment]
This should now be resolved through changes in the space data (PR #222 ). Issue closed - please reopen if there are still problems :smile:
