### ISSUE TITLE
XML_Toolkit: Add deafult value for R-value

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#174]
add R=0.5 as default
![image](https://user-images.githubusercontent.com/26113670/51386231-9f2a6980-1b19-11e9-8c58-db2ba85e82a9.png)

**Comment by FraserGreenroyd** [comment]
@michaldengusiak do we want 0.5 as the default, or do we want to put it to -1 to show that an error occurred in the calc.?

**Comment by michaldengusiak** [comment]
ok lets try `-1.0`, this might still fulfill  and comply with gbXML validator
