### ISSUE TITLE
XML_Toolkit: Pull Add Opening Name 

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#186]
We missing opening's name in Pull XML

![image](https://user-images.githubusercontent.com/26113670/51831180-65abe800-22e9-11e9-941f-e133a7d6cae9.png)
we have
![image](https://user-images.githubusercontent.com/26113670/51831216-7c523f00-22e9-11e9-93fc-84053514bc78.png)

**Comment by FraserGreenroyd** [comment]
Hopefully the commit I've added will resolve this.  It will do it in the same way as building elements. I'm aware that the opening name is incorrect in that screenshot but I believe there is a separate issue to resolve that?

If there isn't it should be raised separately 🙂
