### ISSUE TITLE
XML_Toolkit: Allow to add space type to export as option

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#188]
Add IC data from Revits "space type settings"   to transfer through along with geometry in gbmxl. 

We need to review if currently  Revit bring us this information

**Comment by cskinnerBH** [comment]
Thanks for logging this issue Michal. I've been documenting some of the interactions I've been noticing with Revit --> gbXML --> IES. See attached for a OneNote page

[190129 Revit to gbXML to IES Troubleshooting.zip](https://github.com/BHoM/XML_Toolkit/files/2810380/190129.Revit.to.gbXML.to.IES.Troubleshooting.zip)

**Comment by rwemay** [comment]
Great thread. This is another key reason why we’ve moved to our own interop definitions and do not rely on Autodesk or others to write the linkages - they are all either incomplete or inflexible. We’ve been therefore focussing all global efforts on gbXML/BHoM translations globally. Same for structures (some toolkits use XML some go direct through API’s).

**Comment by FraserGreenroyd** [comment]
I feel this will be best implemented as part of our Extended Properties additions for core BHoM. The data about space type settings, if it exists from Revit Toolkit today, will most likely be coming in `CustomData` - and I'm not a fan of adding more reliance on that when we have a possible solution coming up in Extended Properties :smile:

**Comment by FraserGreenroyd** [comment]
These are the enumeration types available in `6.01` schema of gbXML for `SpaceType`. We now have a `SpaceType` enum in the `Space` object within the Environment oM, We would need to get the `SpaceType` set on toolkits pulling and we can raise some issues on that as appropriate. But for now, we would need to match our `SpaceType` enum with the accepted enumeration below. @michaldengusiak and @cskinnerBH can you edit my comment to populate the table below as appropriate? For reference, our `SpaceType` list can be found [here](https://github.com/BHoM/BHoM/blob/master/Environment_oM/Elements/Enums/SpaceType.cs). I have added some as a starting point.

enumeration | 6.01 attribute | Matching BHoM Space Types  
-- | -- | --
enumeration | ActiveStorageHospitalOrHealthcare |  
enumeration | AirOrTrainOrBusBaggageArea |  
enumeration | AirportConcourse |  
enumeration | AtriumEachAdditionalFloor |  
enumeration | AtriumFirstThreeFloors |  
enumeration | AudienceOrSeatingAreaPenitentiary |  
enumeration | AudienceOrSeatingAreaExerciseCenter |  
enumeration | AudienceOrSeatingAreaGymnasium |  
enumeration | AudienceOrSeatingAreaSportsArena |  
enumeration | AudienceOrSeatingAreaConventionCenter |  
enumeration | AudienceOrSeatingAreaMotionPictureTheatre |  
enumeration | AudienceOrSeatingAreaPerformingArtsTheatre |  
enumeration | AudienceOrSeatingAreaReligious |  
enumeration | AudienceOrSeatingAreaPoliceOrFireStations |  
enumeration | AudienceOrSeatingAreaCourtHouse |  
enumeration | AudienceOrSeatingAreaAuditorium |  
enumeration | BankCustomerArea |  Foyer
enumeration | BankingActivityAreaOffice |  
enumeration | BarberAndBeautyParlor |  
enumeration | CardFileAndCataloguingLibrary |  
enumeration | ClassroomOrLectureOrTrainingPenitentiary |  
enumeration | ClassroomOrLectureOrTraining |  
enumeration | ConfinementCellsPenitentiary |  
enumeration | ConfinementCellsCourtHouse |  
enumeration | ConferenceMeetingOrMultipurpose |  
enumeration | CorridorOrTransition |  Circulation
enumeration | CorridorOrTransitionManufacturingFacility |  Circulation
enumeration | CorridorsWithPatientWaitingExamHospitalOrHealthcare |  Circulation
enumeration | CourtSportsAreaSportsArena |  
enumeration | CourtroomCourtHouse |  
enumeration | DepartmentStoreSalesAreaRetail |  
enumeration | DetailedManufacturingFacility |  
enumeration | DiningArea |  
enumeration | DiningAreaHotel |  
enumeration | DiningAreaFamilyDining |  
enumeration | DiningAreaLoungeOrLeisureDining |  
enumeration | DiningAreaMotel |  
enumeration | DiningAreaTransportation |  
enumeration | DiningAreaPenitentiary |  
enumeration | DiningAreaCivilServices |  
enumeration | DormitoryBedroom |  
enumeration | DormitoryStudyHall |  
enumeration | DressingOrLockerOrFittingRoomGymnasium |  
enumeration | DressingOrLockerOrFittingRoomCourtHouse |  
enumeration | DressingOrLockerOrFittingRoomPerformingArtsTheatre |  
enumeration | DressingOrLockerOrFittingRoomAuditorium |  
enumeration | DressingOrLockerOrFittingRoomExerciseCenter |  
enumeration | ElectricalOrMechanical |  
enumeration | ElevatorLobbies |  
enumeration | EmergencyHospitalOrHealthcare |  
enumeration | EquipmentRoomManufacturingFacility |  
enumeration | ExamOrTreatmentHospitalOrHealthcare |  
enumeration | ExcerciseAreaExerciseCenter |  
enumeration | ExcerciseAreaGymnasium |  
enumeration | ExhibitSpaceConventionCenter |  
enumeration | FellowshipHallReligiousBuildings |  
enumeration | FineMaterialWarehouse |  
enumeration | FineMerchandiseSalesAreaRetail |  
enumeration | FireStationEngineRoomPoliceOrFireStation |  
enumeration | FoodPreparation |  
enumeration | GarageServiceOrRepairAutomotiveFacility |  
enumeration | GeneralHighBayManufacturingFacility |  
enumeration | GeneralLowBayManufacturingFacility |  
enumeration | GeneralExhibitionMuseum |  
enumeration | HospitalNurseryHospitalOrHealthcare |  
enumeration | HospitalOrMedicalSuppliesHospitalOrHealthcare |  
enumeration | HospitalOrRadiologyHospitalOrHealthcare |  
enumeration | HotelOrConferenceCenterConferenceOrMeeting |  
enumeration | InactiveStorage |  
enumeration | JudgesChambersCourtHouse |  
enumeration | LaboratoryOffice |  
enumeration | LaundryIroningAndSorting |  
enumeration | LaundryWashingHospitalOrHealthcare |  
enumeration | LibraryAudioVisualLibraryAudioVisual |  
enumeration | LivingQuartersDormitory |  
enumeration | LivingQuartersMotel |  
enumeration | LivingQuartersHotel |  
enumeration | Lobby |  
enumeration | LobbyReligiousBuildings |  
enumeration | LobbyMotionPictureTheatre |  
enumeration | LobbyAuditorium |  
enumeration | LobbyPerformingArtsTheatre |  
enumeration | LobbyPostOffice |  
enumeration | LobbyHotel |  
enumeration | LoungeOrRecreation |  
enumeration | MallConcourseSalesAreaRetail |  
enumeration | MassMerchandisingSalesAreaRetail |  
enumeration | MediumOrBulkyMaterialWarehouse |  
enumeration | MerchandisingSalesAreaRetail |  
enumeration | MuseumAndGalleryStorage |  
enumeration | NurseStationHospitalOrHealthcare |  
enumeration | OfficeEnclosed |  
enumeration | OfficeOpenPlan |  
enumeration | OfficeCommonActivityAreasInactiveStorage |  
enumeration | OperatingRoomHospitalOrHealthcare |  
enumeration | OtherTelevisedPlayingAreaSportsArena |  
enumeration | ParkingAreaAttendantOnlyParkingGarage |  
enumeration | ParkingAreaPedestrianParkingGarage |  
enumeration | PatientRoomHospitalOrHealthcare |  
enumeration | PersonalServicesSalesAreaRetail |  
enumeration | PharmacyHospitalOrHealthcare |  
enumeration | PhysicalTherapyHospitalOrHealthcare |  
enumeration | PlayingAreaGymnasium |  
enumeration | Plenum |  
enumeration | PoliceStationLaboratoryPoliceOrFireStations |  
enumeration | PublicAndStaffLoungeHospitalOrHealthcare |  
enumeration | ReadingAreaLibrary |  
enumeration | ReceptionOrWaitingTransportation |  
enumeration | ReceptionOrWaitingMotel |  
enumeration | ReceptionOrWaitingHotel |  
enumeration | RecoveryHospitalOrHealthcare |  
enumeration | RestorationMuseum |  
enumeration | Restrooms |  
enumeration | RingSportsAreaSportsArena |  
enumeration | ServerRoom |  
enumeration | SleepingQuartersPoliceOrFireStation |  
enumeration | SortingAreaPostOffice |  
enumeration | SpecialtyStoreSalesAreaRetail |  
enumeration | StacksLibrary |  
enumeration | StairsInactive |  
enumeration | Stairway |  
enumeration | SupermarketSalesAreaRetail |  
enumeration | TerminalTicketCounterTransportation |  
enumeration | WorkshopWorkshop |  
enumeration | WorshipPulpitChoirReligious

**Comment by michaldengusiak** [comment]
@FraserGreenroyd 

our `SpaceType` list that can be found [here](https://github.com/BHoM/BHoM/blob/master/Environment_oM/Elements/Enums/SpaceType.cs) refers to our own space types approach that use... the one you referencing in 6.01 attribute is inspired by US ASHRAE 90.1 so this is will be more alternative... we should provide a mechanism to get mapping for various spaces types: ASHRAE 90.1, PartL, DIN etc... however, this is a good step forward and I am now updating your list above

**Comment by FraserGreenroyd** [comment]
Have discussed with @cskinnerBH and as there's been no action on this in 1.5 years, it is unlikely we will resolve this with the differences between BHoM space types and gbXML space types. If further information is available to help with this issue please feel free to reopen :smile:
