### ISSUE TITLE
XML_Toolkit: Make agnostic XML Serialization

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#199]
XML Serialisation make  software agnostic

```
    public partial class GBXMLSerializer
Line 148
```
update to new software agnostic approach and read `SpaceProperty `Name instead of custom data

@FraserGreenroyd 
we have to add extended properties to store data from Revit Space or Add to TAS_Toolkit required to  Custom data..
we can not test gbXML further until we fix this

**Comment by FraserGreenroyd** [comment]
@michaldengusiak that is a partial class, which file is it in? I'm guessing `BuildingElement.cs` of serialisation?

Agreed we will need to raise specific tasks against Revit, XML, and TAS and Env_Engine to update based on extended properties once they are merged in.

**Comment by michaldengusiak** [comment]
@FraserGreenroyd  yes correct
seems without this extended properties we stuck... 

I just found places where we need to adjust:

`\XML_Engine\Convert\Environment_oM\ElementType.cs line 54`
`\TAS_Engine\Convert\Environment_oM\Opening.cs line 53`
`\TAS_Engine\Convert\Environment_oM\BuildingElement.cs line 51`

**Comment by FraserGreenroyd** [comment]
Agreed. Good to get a handle of where we need to make changes across here, TAS and Revit as we find them to make the final upgrade a bit smoother.

**Comment by FraserGreenroyd** [comment]
It appears this was handled during the April refactoring so no longer an issue.
