### ISSUE TITLE
XML_Toolkit: Thickness Units

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#203]
We importing Meters from TAS however we use milimters in XML  we need to adjust 

`<Thickness unit="Millimeters">0.00600000005215406</Thickness>`

**Comment by FraserGreenroyd** [comment]
Question - do we need to adjust XML where the schema is expecting mm, or TAS to provide us input in mm? If we need to adjust here in XML what do we need to do exactly to resolve the thickness? :smile:

**Comment by rwemay** [comment]
Hi guys, we should be using default SI units in BHoM so metres. The (yet to be fleshed out) Units_Engine will then house and deal with any necessary conversions. 

This might not apply in this case as its XML Toolkit rather than BHoM proper but thought Id mention just in case.
