### ISSUE TITLE
XML_Toolkit: Openings missing Name and CADObjectId 

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#204]
we missing data for openings

```
        <CADObjectId />
        <Name />
      </Opening>
```

we should have 

        <CADObjectId>WinInst: SIM_EXT_GLZ [721906]</CADObjectId>
        <Name>Opening-1</Name>
      </Opening>

_* please note that CADObjectId should replicate Revit Naming (BuildingElement Type Name + {ElementID]) approach so we have unified and replaceable  system_

**Comment by FraserGreenroyd** [comment]
Following discussion, may need to review on TAS pull.
