### ISSUE TITLE
XML_Toolkit: WindowType values adjustment

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#205]
we have currently 
```
  <WindowType id="window-Glazing">
    <Name>Glazing</Name>
    <Description>Standard Dbl Glazed</Description>
    <U-value unit="WPerSquareMeterK">0</U-value>
    <SolarHeatGainCoeff unit="Fraction">0</SolarHeatGainCoeff>
    <Transmittance type="Visible" unit="Fraction" surfaceType="Both">0</Transmittance>
```

we should use Environment_oM following data:

```
  <WindowType id="*Clean (EnvironmentContext TypeName)">
    <Name>*EnvironmentContext TypeName</Name>
    <Description>Standard Dbl Glazed from EnvContext</Description>
    <U-value unit="WPerSquareMeterK">*BuildingElementAnalyticalProperties UValue</U-value>
    <SolarHeatGainCoeff unit="Fraction">*BuildingElementAnalyticalProperties GValue</SolarHeatGainCoeff>
    <Transmittance type="Visible" unit="Fraction" surfaceType="Both">*BuildingElementAnalyticalProperties LTValue </Transmittance>
```
seems it was implemented so we have to review where is broken link

For properties from Analytical, use `-1` for error values not `0`

**Comment by FraserGreenroyd** [comment]
I suspect this might be something from where we've pulled data from not containing the right data so it uses defaults? We'll have to take a look :smile:

**Comment by michaldengusiak** [comment]
ok I reviewed data from Tas and we have them included both BuildingElement and in openings: UValue, gValue, LtValue

![image](https://user-images.githubusercontent.com/26113670/52640722-0fd16580-2ecf-11e9-805a-b88574470117.png)

**Comment by michaldengusiak** [comment]
ok we need to adjust updating opening construction in current BHoM set up

sample here
