### ISSUE TITLE
XML_Toolkit: TAS export fix GLZ wall to window

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#209]
Adjustment to keep wall name:

![image](https://user-images.githubusercontent.com/26113670/52821495-dc493380-30a6-11e9-8846-fbdeb18d8cab.png)

**Comment by michaldengusiak** [comment]
ok I reviewed and `Basic Wall: SIM_INT_GLZ` name should be used

![image](https://user-images.githubusercontent.com/26113670/52857313-b52e4880-311e-11e9-83ef-68b73a8979e0.png)

**Comment by FraserGreenroyd** [comment]
![image](https://user-images.githubusercontent.com/18049174/52862943-5cff4280-312e-11e9-88bb-e187a7ac8ef7.png)
