### ISSUE TITLE
XML_Toolkit: Wrong Normals

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#212]
As you can see we have wrong normals 
![image](https://user-images.githubusercontent.com/26113670/52858204-69c96980-3121-11e9-8b3d-4c637c9efe84.png)

![image](https://user-images.githubusercontent.com/26113670/52858196-63d38880-3121-11e9-95fd-85cc301c71c3.png)

test case use example from #209

**Comment by FraserGreenroyd** [comment]
Fully tested against test case from #209 provided. Test is correctly identifying the normal is pointing away from the space on all elements identified and is correctly flipping/not flipping as appropriate. The visualisation within TAS appears to be incorrect from a TAS perspective. A bug within the code base for XML or the Env_Engine has failed to reveal any issue with these BuildingElements normals. Issue closed.

**Comment by michaldengusiak** [comment]
@

**Comment by FraserGreenroyd** [comment]
@michaldengusiak then we'll need smaller test cases for it - as I said in my closing comment, the code is identifying that the normal points away from the space on that model and therefore cannot correct it if it cannot identify that it's wrong.

**Comment by FraserGreenroyd** [comment]
@michaldengusiak I believe this issue is now resolved following our investigation into normals earlier in the week?

**Comment by michaldengusiak** [comment]
@FraserGreenroyd correct Solved!
