### ISSUE TITLE
XML_Toolkit: Exposed to Sun error

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#223]
All external surfaces are not exposed to sun:

we have now
`    <Surface surfaceType="ExteriorWall" exposedToSun="false" id="Panel-15">`

should be
`    <Surface surfaceType="ExteriorWall" exposedToSun="true" id="Panel-15">`

![image](https://user-images.githubusercontent.com/26113670/53325845-18b53480-38dc-11e9-908a-b94248438e18.png)

**Comment by FraserGreenroyd** [comment]
This is not an XML issue as this function is provided by the `Environment_Engine`. I will open an issue there as well.

**Comment by FraserGreenroyd** [comment]
See https://github.com/BHoM/BHoM_Engine/issues/821 for engine issue.
