### ISSUE TITLE
XML_Toolkit: Use ElementID for Space CADObjectID

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#237]
we have 
```
        <Name>01_030 Space</Name>
        <Description>None</Description>
        <CADObjectId>FIX CAD OBJECT ID FOR SPACE</CADObjectId>
```
should use:
Description: EnvironmentContextProperties Description
CADObjectId: EnvironmentContextProperties ElementID

+ add protection if data not available

**Comment by michaldengusiak** [comment]
we need to address this again

```
        <Name>00_001 WC</Name>
        <Description>None</Description>
        <CADObjectId>[00_001 WC]</CADObjectId>
      </Space>
```

should be 


```
        <Name>00_001 WC</Name>
        <Description>I love this space</Description>
        <CADObjectId>707673</CADObjectId>
      </Space>
```

**Comment by FraserGreenroyd** [comment]
CAD object ID for space currently correct to existing implementation. Changes need to be made to allow spaces to be pushed appropriately - until then space data from the panels is used appropriately.
