### ISSUE TITLE
XML_Toolkit: ExportType Evolvement

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#239]
@FraserGreenroyd 
We need to adjust our `ExportType ` Currently we have Undefined, gbXMLTAS, gbXMLIES.
This could be a bit misleading. 
Let's keep this as live thread and we bring all steps and fixes that are implemented  and at the end we will move this into Documentation before we close this. 
Please add anything we do in each type below

## gbXMLTAS
is in fact native gbXML without construction as per Revit export so our standard 
- fixing normals
## gbXMLIES
`gbXMLIES` is gbXMLTAS + all ies specific fixes as follow:
- replacing glazed building elements wall, floor, roof... `GLZ` with Curtain Wall approach so inserting  (*wall, floor is better than curtain wall as snapping is more accurate)
<img src="https://user-images.githubusercontent.com/26113670/53685894-98963100-3d18-11e9-92bf-85245725a01f.png" width=260>

- opening into BuildingElement replace SLD items like Doors, Windows with separate new Building Element to capture different construction
- replace `Air` walls, floors and make then surfaceTypeEnum: Air (*we prefer to draw with Air Walls,Floor for better snapping see here as gbXML export centre line)
<img src="https://user-images.githubusercontent.com/26113670/53685876-608eee00-3d18-11e9-8e4a-bb482f23f813.png" width=260>
- fixing normals

## Conclusion
We need to implement new ExportType: `Custom` that will allow to input all fixes we want to have from above. As I might want in TAS to have replace GLZ element as Curtain Wall etc...
Obiousley we will add predefine versions for e+/OpenStudio but we need to have one `custom `option.

Maybe would be worthwhile to have specific fixes set up as Enum `CustomFixesTypes `to allow easy selection and then as list connecting to `Custom` Node. 
As I am in charge of discipline content and you control Toolkit structure this is for you to decide how this should be implemented.

This will allow 100% flexibility and modularity there will be a lot of user of HAP, Dialux, SolarComputer in future so let's make this change  sooner than later.

**Comment by FraserGreenroyd** [comment]
I agree good to capture the tool specific fixes we're doing. Not sure on a custom though, that might get tricky to add and filter through for different fixes but something we can play with for sure :smile: I'll add as I find some/think of some.

Maybe one we could do is `default` which just provides a v6.01 (or currently targeted version when that changes) compliant file with no fixes?

**Comment by FraserGreenroyd** [comment]
I think this can be linked closer to the #257 question about an adapter settings similar to Revit Toolkit. This would also allow for more export types similar to what @emidio-piermarini has been asking about :smile:

**Comment by FraserGreenroyd** [comment]
Closing as XML Settings brought in as part of #257 have provided us the ability to evolve the export type by adding settings as required. New issues can be raised as and when new settings are required.
