### ISSUE TITLE
XML_Toolkit: Current capability status

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#242]
Lets keep here visual capability based on SAM template as benchmark:
This is current Revit SAM export status
![image](https://user-images.githubusercontent.com/26113670/53798568-6828df80-3f30-11e9-8477-4b2e7a985cd2.png)

**Comment by michaldengusiak** [comment]
I am happy to add today to current capability list this...
our model is now appearing in OpenStudio....and starts!!!...

![image](https://user-images.githubusercontent.com/26113670/54298192-35c25680-45b0-11e9-9f3d-c395a6656fec.png)

<img src="https://user-images.githubusercontent.com/26113670/54298577-e7fa1e00-45b0-11e9-9d90-fd90ea3a1ddb.png" width=360>

**Comment by michaldengusiak** [comment]
one more item to our list
![image](https://user-images.githubusercontent.com/26113670/54374817-d465ba80-4677-11e9-8d93-0bbd4ff8da8e.png)

**Comment by FraserGreenroyd** [comment]
Our capability has now advanced past this issue so am closing to keep the issue list tidy :smile:
