### ISSUE TITLE
XML_Toolkit: Opening Issue taking to large area normally when come from Curtain Wall

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#243]
Implement check for opening size to be less than host element

referenced here but aslo valid for TAS..etc
https://github.com/BuroHappoldEngineering/EnergyPlus_Toolkit/issues/6

**Comment by FraserGreenroyd** [comment]
@MajaLindroth as discussed yesterday, here are some pointers on this task:

There are some offset methods available in the Geometry Engine which @RasmusCanfjorden has successfully used in other work. These should be used here when handling curtain walls or holes - or other opening types who's edges are coincident with the edges of the panels.

I would recommend we do an `openingOffset` setting that takes in what the offsetting is but default it to `0.001`
