### ISSUE TITLE
XML_Toolkit: adjust geometry and cut existing opening from new opening

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#247]
Currently when we have GLZ wall that contain openings: Door or Window is causing overlap
We need to cut from newly created Opening existing opening to avoid overlaps

![image](https://user-images.githubusercontent.com/26113670/54290254-921e7980-45a2-11e9-800d-2764d600e660.png)

here is image
we have 3 openings here however ...door and windows does not look right
![image](https://user-images.githubusercontent.com/26113670/54290042-2e944c00-45a2-11e9-9bb3-5cdfacf46d12.png)

after I delete new opening we have proper elements
![image](https://user-images.githubusercontent.com/26113670/54290002-1ae8e580-45a2-11e9-91e1-c607102009fb.png)

Actions: when we generate opening we need to cut off existing shapes

**Comment by rboulton-BH** [comment]
I have just come across this issue for TQEC. I have modelled a fully glazed wall with transfer grills as a wall of type SIM_INT_GLZ with Doors placed at high level. The Push to XML fails only when I set "replaceCurtainWalls" is set to True. Workaround for now is to change the wall type to something opaque and to manually draw in windows around the doors.
![image](https://user-images.githubusercontent.com/26925641/66302997-eb107f00-e8f1-11e9-9ae6-a7034d08a5aa.png)
![image](https://user-images.githubusercontent.com/26925641/66303084-227f2b80-e8f2-11e9-812f-a217b2c65fc5.png)
