### ISSUE TITLE
XML_Toolkit: Adapter settings

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/XML_Toolkit#257]
I believe we can make XML Toolkit more powerful with the inclusion of adapter settings, similar to Revit Toolkit and others.

These settings would detail whether we are producing a new XML file from scratch, over-writing some parts of an existing file, appending to an existing file, or other such actions as we can envisage.

This would also allow our XML Toolkit push structure to better match other toolkits, as at the moment everything is set up to work with the `DocumentBuilder` object - something we have discussed removing in the past but not got round to doing.

So this issue is for that discussion of finally agreeing a removal process for `DocumentBuilder` and putting in some adapter settings to enhance XML Toolkit's capabilities.

**Comment by FraserGreenroyd** [comment]
So this is no longer a question but something to be achieved as part of the `2.3` release.

Adapter Settings should allow for:
 - [ ] Replacing Panels with full openings if they are Curtain Walls (currently used on IES export)
 - [ ] Including or excluding constructions and material data (currently used on IES export)

Eventually we will also include XML schema options when new XML schema are available.

**Comment by BingWangUS** [comment]
Hi, we would like to have an option to select the unit system (SI or IP), something similar to the option of TAS or IES type, to make it more powerful when applying in US projects. Thanks.
