### ISSUE TITLE
XML_Toolkit: Space ID conflict with IES/Suncast

### ISSUE THREAD

**Issue by cskinnerBH** [BHoM/XML_Toolkit#258]
Having an issue with the Space ID assigned to spaces when running Suncast in IES. I get an invalid space ID error. The issue is resolved after manually removing the hyphens in the Space ID. Is it possible to use a different Space ID naming scheme when the gbXML export is flagged for IES?

I assume the issue is in `Space.cs` in `Environment_oM`

**Comment by michaldengusiak** [comment]
Yes, this is logged and on our list to fix... it should and will reference Revit Element Id rather what we have now name with underscores or any cadobject id if from other tool if not from Revit 


https://github.com/BHoM/XML_Toolkit/issues/237

**Comment by FraserGreenroyd** [comment]
@michaldengusiak no that's not the ID @cskinnerBH is referring to - he's referring to the space ID itself, not the CAD Object ID. I'll get this fixed for a PR @cskinnerBH

**Comment by FraserGreenroyd** [comment]
@cskinnerBH I can't add you as a reviewer to the PR because you're not a member of the relevant organisation but see link below to review as you wish :smile:

https://github.com/BHoM/XML_Toolkit/pull/259
