### ISSUE TITLE
XML_Toolkit: Local shade ID conflict with IES/Suncast

### ISSUE THREAD

**Issue by JAbboudBH** [BHoM/XML_Toolkit#284]
Related to #258. 

Similar issue is occurring where local shades are being imported with hyphens.

**Comment by michaldengusiak** [comment]
can you provide example of your gbXML and error in IES, thanks
ps. your Github profile is not set up

**Comment by FraserGreenroyd** [comment]
@JAbboudBH this has been raised for PR should you wish to review alongside the people nominated :smile:

**Comment by rwemay** [comment]
This sounds like something that's software specific, and possibly not surprising the different software is implementing a schema in different ways (that's one of the main problems with IFC, for example). It might be worth starting to think about some software specific adapters that are dependent on the gbXML_Toolkit, so the software specifics can be applied at the software toolkit end.

**Comment by FraserGreenroyd** [comment]
@rwemay see #257 and #323 which will resolve this.
