### ISSUE TITLE
XML_Toolkit: Pull XML remove space identifier.

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#289]
we should have names format like `00_001 WC`

we should pull not from ID
`<Space zoneIdRef="ZoneID" conditionType="Unconditioned" buildingStoreyIdRef="Level-level00" id="Space00_001WC">`

but from name

```
        <Name>00_001 WC</Name>
        <Description>None</Description>
        <CADObjectId>[00_001 WC]</CADObjectId>
```

![image](https://user-images.githubusercontent.com/26113670/59599828-6e198980-90f7-11e9-8fad-d043365acfd0.png)

 [test file](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/XML_Toolkit/XML_Toolkit-Issue290%20PullOpening?csf=1&e=YGf3kw)

**Comment by michaldengusiak** [comment]
I tested again file and we have right now... and when we pull Space we have wrong Name, this is cause of our issue, ok issue is now identified

```
        <Name>Space00_001WC</Name>
        <Description>None</Description>
        <CADObjectId>[Space00_001WC]</CADObjectId>
```

**Comment by FraserGreenroyd** [comment]
I suspect the name is correct because that's what will be stored in the XML file - the XML pull is only pulling information from an XML file that has been deserialised, it's not adding any new parts? Therefore the name cannot be wrong because it's from the file, not from our code 😖

**Comment by michaldengusiak** [comment]
I pull from  first gbXML 

this what we have
```
        <Name>00_001 WC</Name>
        <Description>None</Description>
        <CADObjectId>[00_001 WC]</CADObjectId>
```

when I now push to new gbXML we have this

```
        <Name>Space00_001WC</Name>
        <Description>None</Description>
        <CADObjectId>[Space00_001WC]</CADObjectId>
      </Space>
```
so we lose data on pull or when we push...all data exist

I will upload test file for both here

**Comment by FraserGreenroyd** [comment]
Test file will be helpful.

I would ask, what is the `AdjacentSpaceID` of the panels - that is what we pull into the `ConnectedSpaces` for the panels when pulling from XML and what we probably then push back out again - if you pulled and pushed a second time I would hypothesise you'll end up with `SpaceSpace00_001WC`

**Comment by michaldengusiak** [comment]
ok I found issue... if we rely on Panel Connected Spaces we need to modify our current Panel Connected Spaces = which is AdjacentSpaceId to SpaceName, this will solve this issue and allow us pull and push or the same file without data change

![image](https://user-images.githubusercontent.com/26113670/59630758-0c304280-913e-11e9-9c94-aa037fb4ba4f.png)

**Comment by FraserGreenroyd** [comment]
In that case I would argue that it needs to be an `Environment_Engine` issue to have a modify component which will modify a panels connected spaces where they meet a criteria to replace them with a new name, rather than something for the XML Toolkit to handle?

**Comment by michaldengusiak** [comment]
sure if this need to go to Engine...this is fine... I always start with final tool is this need to go up than is fine...

**Comment by FraserGreenroyd** [comment]
That would be my recommendation cause arguably that is a modification of the panel after it is pulled which is best done by users on a case by case basis. We can then set up our default scripts which will tidy up space names, etc. :smile:
Maybe also a component for cleaning chars from a space name? So users can specific a string to remove from a space name (in this case it would be `Space`) to tidy them up?

We might also want to look long term at the benefit of adding `Space` as a precursor to the adjacent space IDs when pushing gbXML - maybe something to have a quick chat on tomorrow morning? :smile:

**Comment by al-fisher** [comment]
> arguably that is a modification of the panel after it is pulled which is best done by users on a case by case basis

Agreed. This is best practice and to allow for future reuse

**Comment by FraserGreenroyd** [comment]
Closed as issue moved to Env_Engine.
