### ISSUE TITLE
Environment_Engine: Fix Air Surfaces for External Surfaces

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#294]
Recognize Air surfaces that are adj to roof and contain one adj space and replace from AIR to appropriate Roof that is i contact with Air...

![image](https://user-images.githubusercontent.com/26113670/57010087-b4239800-6bf2-11e9-91ac-360dabece8a8.png)

[test file](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Environment_Engine/Environment_Engine-Issue927-FixAirSurfacesforExternalSurfaces?csf=1&e=SqnRdU)

**Comment by FraserGreenroyd** [comment]
Fixed in PR coming momentarily:
![image](https://user-images.githubusercontent.com/18049174/62472819-760cb600-b797-11e9-9fc4-4207800597fb.png)
