### ISSUE TITLE
Environment_Engine: ChangeSpace CADObjectID for Spaces

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#295]
currently we use Name but need Revit ElementID when pulling from Revit

**Comment by FraserGreenroyd** [comment]
On reflection with @MajaLindroth earlier this week, it was decided that no action will be taken on this issue at this time. The `CADObjectID` reference within a gbXML schema provides us with the ability to refer back to the original object in the original CAD drawing, which can still be achieved with the current functionality of using the space name when joining panels up.

Revit's ElementID is only available in circumstances where models were pulled into BHoM from Revit, but would not exist in other software implementations.

Equally, spaces as a concept in BHoM do not contain geometry, so their current CAD data is not mapped across and we push through the panels grouped as closed volumes. Thus, obtaining the original CAD ID for spaces is difficult, and the current implementation provides us with the functionality we require from the schema.

As such, I am closing this issue as it will not be resolved in this milestone, or any upcoming milestones for the foreseeable future :smile:
