### ISSUE TITLE
XML_Toolkit: Macro test folder

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/XML_Toolkit#300]
Include push and pull scripts for macro testing.

 - [x] Pull from XML
 - [x] Push to XML

**Comment by michaldengusiak** [comment]
@FraserGreenroyd 

[I created folders and setting up examples](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/XML_Toolkit/_Macro?csf=1&e=VSrlGI)

**Comment by FraserGreenroyd** [comment]
Reviewed and updated GH file - am happy :smile:

**Comment by FraserGreenroyd** [comment]
I can't load the dynamo thing properly - @michaldengusiak can you update the Dynamo file in this folder: [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FXML%5FToolkit%2F%5FMacro%2FPush)

To not include anything to do with Revit please. Just pull XML into BHoM canvas is fine :smile:

**Comment by michaldengusiak** [comment]
files are fine...I saved correct reference for file and removed Revit... it does not work right now as we need to fix issue #305 
I will add GH and Excel as well but awaiting some Excel fix as well. 

![image](https://user-images.githubusercontent.com/26113670/60161986-7dcc5880-97f0-11e9-8dcf-ae72d86a2ebb.png)

**Comment by FraserGreenroyd** [comment]
That's great, cheers @michaldengusiak :smile:

Don't worry to much over Excel, I think the concept will be ok and this is for macro testing purposes.

GH is handled by the push script you did (pull XML -> push XML) so I just copied that over :smile:
