### ISSUE TITLE
XML_Toolkit: Zone TypeCode

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#304]
We will use this for Zones as our Space IC_ThermalTemplate as reference
link to out space types..
```
S00_Unconditioned
S01_Auditorium
S02_Bathroom
S03_Bedroom
S04_Breakout
```
and can fill for each Zone gbXML
DesignCoolT - Design temperature for cooling
DesignHeatT - Design temperature for heating

**Comment by FraserGreenroyd** [comment]
This will require a full mapping drafted in this issue to relate our Space Types to the Zone Type code before anything can be implemented.

**Comment by michaldengusiak** [comment]
idea is that Zone Types are our types 1:1
no translation needed so we use public enum SpaceType for a  gbXML TypeCode

```
<xsd:element name="TypeCode" type="xsd:string">
  <xsd:annotation>
    <xsd:documentation>User/project defined Code for Space or Zone.</xsd:documentation>
  </xsd:annotation>
</xsd:element>
```

**Comment by FraserGreenroyd** [comment]
1:1 is fine but I doubt they're called the same thing in the gbXML schema for 6.01? The table similar to space types that we've done before is what we need to achieve this :smile:

**Comment by FraserGreenroyd** [comment]
Zone types are no longer a thing within Environments oM at this stage, so little work can be done to integrate Zone Type Codes into the XML push. Currently not sought as a feature by many, so closing for now. If further information is able to be brought to light to help resolve this issue in a better way feel free to reopen :smile:
