### ISSUE TITLE
XML_Toolkit: Adapter inputs

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#307]
When we change XML adapter name, I do not recall this one?

all my scripts still use old naming and luckily this do not update, as old names make more sense than new ones... we connecting `file name` and not `project name` etc. we need to revert this 

![image](https://user-images.githubusercontent.com/26113670/60198289-1e466b00-9839-11e9-8a3d-bfebd012f743.png)

**Comment by FraserGreenroyd** [comment]
I think this is something @LivAndersson will be able to assist with as well :smile:

**Comment by LivAndersson** [comment]
I'm on it!

**Comment by LivAndersson** [comment]
What exactly are people supposed to specify in "exportDetail"?

**Comment by FraserGreenroyd** [comment]
Whether they want a full export (everything in one file), or a shell export (external walls only, for doing building shell early-stage calcs.), or a space-by-space export (useful for SAP type analysis) where each file is an individual space from the model being pushed. Does that make sense?

**Comment by LivAndersson** [comment]
How is that then different to exportType?

**Comment by FraserGreenroyd** [comment]
Export type is whether or not they want TAS specific or IES specific - however, this will soon be replaced by XML Settings (#257) so it will become clearer. You could do some basic rewording/description attributes on this for now as I'm hoping to do #257 in the next sprint :smile:
