### ISSUE TITLE
XML_Toolkit: Error Push gbXML with new openings

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#325]
#### Description:

when I get our template with more complex case it return error here when try to export.
![image](https://user-images.githubusercontent.com/26113670/61290767-919e2580-a7c4-11e9-852f-68a7f28f19c9.png)
geometry looks good, I save this example as test case
I save example

#### How to replicate:

Runs Script

#### Test file(s):

[TestFile](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/XML_Toolkit/XML_Toolkit-Issue325%20ErrorPushgbXMLwithnewopenings?csf=1&e=9TIwEM)

**Comment by michaldengusiak** [comment]
OK I did more test and when I remove donut space it works fine..we should then add this check to our process

from
![image](https://user-images.githubusercontent.com/26113670/61292189-7b926400-a7c8-11e9-94f4-96c00ead1d34.png)

to
![image](https://user-images.githubusercontent.com/26113670/61292175-71706580-a7c8-11e9-81cc-f93eb019a3cc.png)

![image](https://user-images.githubusercontent.com/26113670/61292222-8baa4380-a7c8-11e9-80b3-3df86d7dbf48.png)

there is one issue with TAS that I logged,
Openstudio, IES seems to be fine


now I reverted back to model with doughnut and works fine...
I suspect issue is with GH and serialisation that remember previous run or some BHoM elements. 
I would like to test someone this example and see if it works fine
@tg359  or @FraserGreenroyd 

![image](https://user-images.githubusercontent.com/26113670/61310267-dbe6cd00-a7eb-11e9-9b0a-9da6978bb4c0.png)

![image](https://user-images.githubusercontent.com/26113670/61310423-2a946700-a7ec-11e9-825b-abb89d478ff2.png)

**Comment by FraserGreenroyd** [comment]
Cannot replicate so looks like a GH serialisation issue.
