### ISSUE TITLE
XML_Toolkit: Missing storey from Panels when push to gbXML

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#329]
#### Description:

Storey is missing in gbXML
![image](https://user-images.githubusercontent.com/26113670/61807247-10343c00-ae31-11e9-8cd6-d5c9245d96cd.png)

#### How to replicate:

run test script

#### Expected behaviour:

we should see correct level for each panel

#### Test file(s):

[test script](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/XML_Toolkit/XML_Toolkit-Issue329-MissingStorey?csf=1&e=NimiZX)

**Comment by FraserGreenroyd** [comment]
Have resolved this issue as it was not a code issue but a GH script issue. Issue closed.
