### ISSUE TITLE
XML_Toolkit: XML_FilePath remove exportType

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#338]
#### Description:

Seems we forgot to remove `exportType` from `XMLFilePath`

#### How to replicate:

run node
![image](https://user-images.githubusercontent.com/26113670/64080829-1222d200-ccf0-11e9-91ee-40a874ba7574.png)

#### Expected behaviour:

file path should not include TAS, IES reference

**Comment by FraserGreenroyd** [comment]
This issue should have been discussed before any code was written or changed because the bigger point has been missed. I am closing this issue as an irrelevant issue not to be fixed, and am raising the correct issue to detail the work that needs to be done. The associated PR has also been closed.
