### ISSUE TITLE
XML_Toolkit: bug XMLSettings includeConstructions 

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#342]
#### Description:

when tick `includeConstruction`  we can not export gbMXL
![image](https://user-images.githubusercontent.com/26113670/64428253-33e2d700-d0ab-11e9-9fa4-153bd0268295.png)
![image](https://user-images.githubusercontent.com/26113670/64428389-83290780-d0ab-11e9-8550-4a394d7f3b98.png)

#### How to replicate:

run gbXML export with constuction

#### Expected behaviour:

export file with default construction if missing and not defined in panels

#### Test file(s):

please use [gbXML_debug1.gh](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/XML_Toolkit/XML_Toolkit-Issue342_ConstructionBug?csf=1&e=yszVAY)

**Comment by FraserGreenroyd** [comment]
Can you provide a test script with internalised panel data? Currently I can't replicate this issue so want to get the data you're using please :smile:

**Comment by michaldengusiak** [comment]
sure here is an [example file](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/XML_Toolkit/XML_Toolkit-Issue342_ConstructionBug?csf=1&e=MMid1k)
