### ISSUE TITLE
Add Air Wall Feature in XML Export Type IES

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/XML_Toolkit#344]
#### Description:
Export Type IES does not currently include conversion of air walls

**Comment by michaldengusiak** [comment]
sure happy to help,

I just re-tested our current template...
where we have air walls and floors

![image](https://user-images.githubusercontent.com/26113670/64510660-9c63cb00-d2da-11e9-9b44-cb9e3ff32833.png)

![image](https://user-images.githubusercontent.com/26113670/64510626-89e99180-d2da-11e9-9831-03670fbd0189.png)

![image](https://user-images.githubusercontent.com/26113670/64510869-fc5a7180-d2da-11e9-8249-58f9f36595f6.png)


![image](https://user-images.githubusercontent.com/26113670/64510668-a08fe880-d2da-11e9-87b1-5b1910c88457.png)
![image](https://user-images.githubusercontent.com/26113670/64510683-a5ed3300-d2da-11e9-8318-de835f6157eb.png)

IES
![image](https://user-images.githubusercontent.com/26113670/64511179-a6d29480-d2db-11e9-87af-0b5dd52e6fb9.png)

TAS
![image](https://user-images.githubusercontent.com/26113670/64511194-b05bfc80-d2db-11e9-8e74-d0b97573d4c2.png)


which conversion are you referring to?

**Comment by FraserGreenroyd** [comment]
@michaldengusiak this is referring to geometry created through primarily Rhino processes, not Revit. This is on my task list for this sprint and I'll get it handled before Thursday.

**Comment by FraserGreenroyd** [comment]
I believe this issue has been resolved as have not heard anything more on it - @kayleighhoude please feel free to reopen/open a new issue if another problem arises :smile:
