### ISSUE TITLE
XML_Toolkit: Planar Tolerance bug

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/XML_Toolkit#348]
#### Description:
Planar Tolerance can occasionally cause a gbXML file to not be produced.

#### How to replicate:
Run @michaldengusiak test script from #342 

#### Expected behaviour:
To be able to change the `PlanarTolerance` within `XMLSettings` and export @michaldengusiak test script.

#### Test file(s):
[Here](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/XML_Toolkit/XML_Toolkit-Issue342_ConstructionBug?csf=1&e=MMid1k)

**Comment by Majalindroth** [comment]
I'll look into it

**Comment by FraserGreenroyd** [comment]
Great, thanks @Majalindroth :smile:
