### ISSUE TITLE
XML_Toolkit: geometry issue prevent from XML push

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#431]
#### Description:

I guess think might be logged in the wrong place but I start here as my aim is to produce XML. 
From my model, I isolated space with the problem. 

I have panels that can make closed brep,

when I connect to push XML there is an error with geometry.
![image](https://user-images.githubusercontent.com/26113670/76766055-4abb6200-678f-11ea-9be7-2d15a86792cb.png)

```
2. This component failed to run properly.
- Error: Object reference not set to an instance of an object.
- Occured in  BH.Engine.Geometry.Query.DiscontinuityPoints(Polyline curve, Double distanceTolerance, Double angleTolerance)
     called from BH.Engine.Geometry.Modify.RemoveLeastSignificantVertices(Polyline polyline, Double smallestAcceptableAngle, Double angleTolerance, Double distanceTolerance)
- Are you sure you have the correct type of inputs? Check their description for more details.
```

I extracted polylines from `Panels `and connected to each function
both of them are working fine, not sure why I have error and where is failing?
Appreciate your help and support,

#### Steps to reproduce:

Run  attached script

#### Expected behaviour:

No error at Push XML

#### Test file(s):

[XML_geometryIssue.zip](https://github.com/BHoM/XML_Toolkit/files/4338551/XML_geometryIssue.zip)

**Comment by MajaLindroth** [comment]
It looks like a offset can't be produced due to invalid geometry, see opening in picture below, OpeningPoly returns null.

I'm closing this issue due to the problem not being solvable by the toolkit.
 
![image](https://user-images.githubusercontent.com/52914659/77340068-ac964180-6d24-11ea-8f83-462873905393.png)
