### ISSUE TITLE
Add support for KML files

### ISSUE THREAD

**Issue by rolyhudson** [BHoM/XML_Toolkit#441]
Would be great to extend the toolkit to support the generation of and eventually reading of KML files for use with Google Earth.
[KML documentation ](https://developers.google.com/kml/documentation/kmlreference)

I propose we focus on a specific current use case: pushing geo referenced mesh objects. 

This is part of a current workflow for modelling and stadium seating bowls. Export to KML is allowing checking against the (sometimes 3d) data in Google Earth.

Sample KML files from this workflow are available [here](https://teams.microsoft.com/_#/files/Bath%20Structures%20Team%202?threadId=19%3A32a9fe4f70e547f9b9432e57a2c81ffd%40thread.skype&ctx=channel&context=KML&rootfolder=%252Fsites%252FStructures-Bath%252FShared%2520Documents%252FBath%2520Structures%2520Team%25202%252FStadia%2520Database%252FStadia%2520models%252FKML)

Currently implemented as a simple `Convert` method using a `StringBuilder` [here](https://github.com/BuroHappoldEngineering/Buildings_Toolkit/blob/RefactoringSeatingModelling/Venue_Engine/Convert/ToKML.cs). Currently this approach is not using `XmlSerializer` but should do to integrate with XML_Toolkit..

Some other minimal requirements below.

Objects required in a KML folder in XML_oM:
- `Style`
- `Polygon`
- `Folder`

Helper method to convert geometry to Geospatial:
`NorthEastDisplacement`

Geometric inputs required to convert from model space to geospatial:
`Latitude` 
`Longitude` 
`NorthVector`
`referencePoint` (in xyz model space)

**Comment by rolyhudson** [comment]
@FraserGreenroyd is that enough detail for you to understand what changes may be needed?

**Comment by FraserGreenroyd** [comment]
Hi @rolyhudson yes that should be enough - I'll let you know when I've got a PR up on resolving #440 so this one can begin :smile:
