### ISSUE TITLE
XML_Toolkit: Incorrect Normals Issue in gbXML

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#444]
#### Description:

I finally manage to fix my Revit Toolkit and can test XML properly now. I run my standard SAM_Template and noticed that now we are issues with Normals... lots of them got wrong orientation... here is list
![image](https://user-images.githubusercontent.com/26113670/80509442-55157200-8971-11ea-9bfb-aaa850cad181.png)

#### Steps to reproduce:

Run run script
![image](https://user-images.githubusercontent.com/26113670/80509989-04524900-8972-11ea-8db4-c3caabdc03f4.png)

#### Expected behaviour:

not errors related to orientation

#### Test file(s):

[Revit_Toolkit_Issue674_1.zip](https://github.com/BHoM/Revit_Toolkit/files/4540486/Revit_Toolkit_Issue674_1.zip)

**Comment by FraserGreenroyd** [comment]
Can I confirm you are working from the latest master @michaldengusiak ? This was an issue with the refactoring PR but was resolved during testing before the PR was merged

**Comment by michaldengusiak** [comment]
Yes,  I just rebuild all 15 min ago when testing Revit Toolkit. I took it from Master.
