### ISSUE TITLE
XML_oM: Inconsistent namespace update

### ISSUE THREAD

**Issue by adecler** [BHoM/XML_Toolkit#445]
#### Description:
In the code, the namespace have been updated to `BH.oM.External.XML.GBXML` but in `Versioning_32.json`, it was updated to `BH.oM.External.XML`. 

This means upgrade of types is currently failing. This is especially a big deal for components using the auto generated constructor as they store the type when saved.

**Comment by FraserGreenroyd** [comment]
@adecler I think the issue might stem from the fact that some components had their namespace changed from `BH.oM.XML` to `BH.oM.External.XML` while the gbXML objects had their namespace changed from `BH.oM.XML` to `BH.oM.External.XML.GBXML`. How should this be handled within the `Versioning_32.json` file to avoid wrongly trying to upgrade the first set of objects past their new namespace?
