### ISSUE TITLE
XML_oM: Name property overridden incorrectly

### ISSUE THREAD

**Issue by adecler** [BHoM/XML_Toolkit#446]
#### Description:
 Some `GBXMLObject` are overriding their `Name` property. Unfortunately, it is done incorrectly, causing serialisation of those objects to fail.
Two things are needed to fix this:
- The `Name` property of `GBXMLObject` should be declared `virtual` so it can be overridden. All properties should now be `virtual` everywhere anyway.
- All children of that class should use the keyword `override` instead of `new` on the `Name` property.

#### Steps to reproduce:
You can see that this is failing by creating a `DummyObject` of that type and trying to serialise it using `ToJson`

#### Expected behaviour:
Serialisation should work once the fix suggested above has been implemented.

### Additional comments
Honestly the XML_oM classes could use a bit of TLC:
- an empty line between each property
- the usual comment delimiters
- descriptions

**Comment by FraserGreenroyd** [comment]
This was done because we had to force an override of the BHoMObject properties to be compliant with both BHoM requirements and the gbXML schema, but agree that now the properties are virtual this should be changed - will get this done today.
