### ISSUE TITLE
KML - meshes with triangular faces fail.

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#463]
Hi @rolyhudson 
I did some test with a different type of geometries and this is not clear for me what are requirements. 
I tested on some model and I got this error for this shape. I would appreciate your advice. I attached my file. 

![image](https://user-images.githubusercontent.com/26113670/82020326-c9922580-9680-11ea-8642-a31b6bf95f7e.png)

[kmlTest_geometryQuestion.zip](https://github.com/BHoM/XML_Toolkit/files/4632700/kmlTest_geometryQuestion.zip)

**Comment by rolyhudson** [comment]
Nothing wrong on your part in terms of the geometry preparation although maybe worth considering how the document will be structured based on how you group or join your meshes. More info on that [here](https://github.com/BHoM/XML_Toolkit/wiki/KML-Getting-started). 

What you identify is a bug / poorly implemented code not correctly handling triangular mesh faces. Updated the name of this issue to reflect that.

This is the result we expect from the file provided in the original question:
![2020-05-15_08-34-13](https://user-images.githubusercontent.com/6618854/82024105-2f81ab80-9687-11ea-98fa-05fdb612505a.jpg)
