### ISSUE TITLE
KML format

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#465]
Should KML not also support to export file as .KML?

https://developers.google.com/kml/documentation/kml_tut

https://developers.google.com/kml/documentation/models

currently it does not work
![image](https://user-images.githubusercontent.com/26113670/82034137-b2116780-9695-11ea-9472-06e3715d9589.png)

**Comment by rolyhudson** [comment]
Probably yes, but we are using the XML_Toolkit so it is a little unclear. 
For now it will output a file with the extension .*xml that will work with Google Earth. 

This issue may come up again when including other xml schemas that use extensions other than .*xml. 
I would suggest that as the KML functionality is currently very limited and there is a fairly painless workaround we wait until it becomes an issue affecting more users and more applications.

**Comment by FraserGreenroyd** [comment]
I am satisfied the provided answer answers the question asked so am going to close this issue as the question is resolved.

I might also add that as a user who might not know what a KML document is, being asked to provide, or required to provide, a file extension that is not `.xml` might be confusing and detract from the XML_Toolkits purpose, which is to convert BHoM objects into the supported XML schemas. As KML is a specific schema of XML, as opposed to its own language or schema, it still makes sense that the final file format is `.xml`

If there is further information to be considered please reopen with said information for discussion.
