### ISSUE TITLE
add protection for Shading and unassigned Panels

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#475]
![image](https://user-images.githubusercontent.com/26113670/83141275-4abcd400-a0e7-11ea-8ce3-2955687686ce.png)

#### Description:

Currently, node does not work without this data, it should still work

**Comment by FraserGreenroyd** [comment]
This will be best handled by removing the gbXML Document Builder requirement as discussed recently with @rolyhudson - this will be planned in for the 4.2 milestone. This will allow us to just push objects into the XML adapter without needing to group them entirely as we currently do with document builders :smile:
