### ISSUE TITLE
XML Apadater for Energyplus Loads Summary

### ISSUE THREAD

**Issue by KentonPhillips-BH** [BHoM/XML_Toolkit#477]
I get the following error when tyring to read a XML file generated by EnergyPlus - "1. The XML Schema you have supplied is not currently supported by the XML Toolkit"

**Error Screenshot**
![image](https://user-images.githubusercontent.com/57185336/83645632-b3410080-a580-11ea-830a-af8b27edc5dc.png)

It would be used be useful to add this schema to the toolkit because it gives us the ability to breakdown the design heating and cooling loads into component contribution. I have attached the summary tables in image format becuase I can not direclty attach them. 

**Screen shot of Summary Table - HTML**
![image](https://user-images.githubusercontent.com/57185336/83646378-8e995880-a581-11ea-805c-63f8166e1c07.png)

**Screen shot of Summary Table - XML**
![image](https://user-images.githubusercontent.com/57185336/83646436-a1139200-a581-11ea-9f98-ad0700d1a95a.png)

**Comment by FraserGreenroyd** [comment]
@KentonPhillips-BH can you share the XML file as well to help identify? As this is a new schema, we won't be able to accomplish this in the 3.2 milestone but we can take a look as a priority for 3.3 :smile:

**Comment by KentonPhillips-BH** [comment]
Please find the xml and html file attached. I realized I can share them if I saved them as txt files. 

[test_Table xml.txt](https://github.com/BHoM/XML_Toolkit/files/4724343/test_Table.xml.txt)
[test_Table html.txt](https://github.com/BHoM/XML_Toolkit/files/4724351/test_Table.html.txt)

Additionally, understood about the milestone scheudule.

**Comment by KentonPhillips-BH** [comment]
I found a work around for the time being. Im using a componentn to conver the XML file into a JSON file. From there I covert the JSON into a BHOM Custom Object. Works pretty good for the time being. 

**XML to JSON to BHOM**
![XMl to BHOM Custom](https://user-images.githubusercontent.com/57185336/83984365-cfd39480-a902-11ea-9b20-feec4701d1a1.PNG)

**Graphing Resutlts**
![Showing zone component summary](https://user-images.githubusercontent.com/57185336/83984369-dcf08380-a902-11ea-90b3-eeed2f40cca9.PNG)
