### ISSUE TITLE
XML_Toolkit: UnitType of GBXMLSettings is not working as expected

### ISSUE THREAD

**Issue by BingWangUS** [BHoM/XML_Toolkit#505]
#### Description:

Found this bug in a recent project application. This setting should change the units in line 2 of the XML file generated but not functioning as expected now.

**Comment by BingWangUS** [comment]
@JAbboudBH FYI this is why Sigal is getting a bigger model in Princeton.

**Comment by FraserGreenroyd** [comment]
What should it change the units to vs what is it currently changing them to @BingWangUS ? Need more information to successfully do a PR on this

**Comment by BingWangUS** [comment]
if(_xmlSettings.UnitType == UnitType.Imperial)
            {
                gbx.TemperatureUnit = "F";
                gbx.LengthUnit = "Feet";
                gbx.AreaUnit = "SquareFeet";
                gbx.VolumeUnit = "CubicFeet";
                gbx.UseSIUnitsForResults = "false";
            }

Took a look at the XML_Toolkit, this was comment out in XML_Adapter\CRUD\Create.cs file.
