### ISSUE TITLE
Unable to generate gbXML possible bug?

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/XML_Toolkit#522]
Hey...after some break decided to rebuild all BHoM and test gbXML.... unfortunately no luck...
I have this simple model
![image](https://user-images.githubusercontent.com/26113670/109398016-038f9800-7932-11eb-9cb9-e4dc5f1bc998.png)
that I am unable to export to gbXML
![image](https://user-images.githubusercontent.com/26113670/109398081-510c0500-7932-11eb-8c7a-1fbd701d2707.png)

however, I checked polyline as per message and all are closed

![image](https://user-images.githubusercontent.com/26113670/109398098-6b45e300-7932-11eb-853f-484506b603fe.png)

there must be sth not right...
Can you let me know what I am doing wrong and assist with this :)?

[gbXML_example.zip](https://github.com/BHoM/XML_Toolkit/files/6055234/gbXML_example.zip)

**Comment by michaelhoehn** [comment]
Hey @michaldengusiak I had a look at the script and think I was able to identify the problem. You are experiencing the error based on the creation of the panel geometry. I think there's a topological dissociation occurring between the panels and their respective edges i.e. the combined panels are confused between their geometric and spatial connectivity properties. I've restructured your original objects and was able to successfully push the XML and preview in AragogXML Viewer using the following changes.  

![image](https://user-images.githubusercontent.com/54593392/109664745-76b82a80-7b3b-11eb-9928-710b9d24b10a.png)

I'm not sure how you originally generated the panels, but if you're working in Rhino/GH might I suggest the following method?
![image](https://user-images.githubusercontent.com/54593392/109666378-22ae4580-7b3d-11eb-8fca-8f10c43ef53f.png)

I was unable to identify any particular bug in the code itself. So if you're happy with this explanation, please close the issue.

**Comment by michaldengusiak** [comment]
@michaelhoehn  thanks for your reply, after rebuild it works. I will review panel set up..
